### ISSUE TITLE
BARDET-BIEDL aganglionic megacolon

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/hpo-annotation-data#2]
On the Monarch page for Bardet-Biedl we have a phenotype "aganglionic megacolon, but I cannot find this phenotype on the associated OMIM page (or in the clinical synopsis).

**Comment by drseb** [comment]
I could not find a lot of evidence for this annotation. @pnrobinson should we remove the line:
OMIM:209900	BARDET-BIEDL SYNDROME					HP:0002251	Aganglionic megacolon			IEA	IEA							OMIM:209900	HPO	Feb 17, 2009	

I found that Orphanet's entry for Hirschsprung has as synonym "Aganglionic megacolon" (http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=388.0) and mentions that  Hirschsprung " ... can also be associated with additional anomalies such as ... limb anomalies (Bardet-Biedl syndrome)... "

**Comment by pnrobinson** [comment]
I corrected this in our annotation. I also do not think the Orphanet entry is correct, at least it does not seem to be the case that BBS1 is associated with megacolon. I sent the Orphanet team a message via their tracker.
