### ISSUE TITLE
remove erroneous zero-padding from common files

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/hpo-annotation-data#84]
i've noticed all the DOIDs are zero-padded.  however this is incorrect.

you can see with this command, that gets you ~7K DOIDs that are not zero-padded:

<pre>
grep -o DOID_[0-9]* doid-edit.owl | sort | uniq | sed 's/DOID_//g' | grep -v ^0
</pre>

can you correct?

**Comment by drseb** [comment]
This is no bug. Have a look at the [HumanDO.obo](http://sourceforge.net/p/diseaseontology/code/HEAD/tree/trunk/HumanDO.obo). These are the IDs of the ontology found in the ontology.
E.g. <code>grep "^id: DOID" HumanDO.obo</code> gives
 
    ...
    id: DOID:0050025
    id: DOID:0050026
    id: DOID:0050032
    ....
    id: DOID:11256
    id: DOID:11257
    id: DOID:11258
    id: DOID:11259
    id: DOID:11260
    id: DOID:11261
    ...

Also the annotation files were created by me from the *big file* that is available from pubmed-browser.

**Comment by cmungall** [comment]
Yep, DO is a mixture. All newer terms are zero-padded, but many older ones are not. However, the annotation files always zero-pad

Here's a case of a discrepancy:

 * [DOID:14330](http://purl.obolibrary.org/obo/DOID_14330) ! Parkinson's disease

Which corresponds to:

DOID-DOID:0014330.tab

with lines like 
```
DOID-DOID:0014330       Parkinson Disease                                       HP:0001278      Orthostatic hypotension                 ITM     ITM                                             Parsed by BioLark from Pubmed abstract (additional info: 2471.233139848726/348). MESHID: D010300        PMID:16906622;PMID:12814332;PMID:21560061;PMID:12654979;PMID:5386267    HPO     11.05.2015
```

We can always build a lookup table when loading but my preference would be to reduce moving parts and fix at source. What do you think?

**Comment by nlwashington** [comment]
in dipper code, i've built a mapping (i do this dynamically by inspecting all the doids from the most-recent doid-edit.owl file, and if there's one that's padded that shouldn't be in the common-disease files, i remove the padding before creating the association.  there are 7685/8944 DOIDs are not zero-padded in the owl file).

**Comment by nlwashington** [comment]
from what i can tell, 2004/2089 of the disease identifiers need replacing to be consistent with doid-edit.owl
