### ISSUE TITLE
fix DOID prefixes in common files

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/hpo-annotation-data#85]
the common files are prefixed like ```DOID-DOID:``` instead of just ```DOID:```.  is there any reason for this?  can this be corrected?  i notice the MESH files are fine with just ```MESH:```.

**Comment by drseb** [comment]
I made this to follow the naming conventions that we have for the rare diseases. Actually the MESH-files are not correctly named here.

**Comment by nlwashington** [comment]
well, it's true for the filename, and i also meant inside the file.  the disease id inside the file is also ```DOID-DOID:``` prefixed.  that seems different to me than what you've done for MESH, or what I see in the rare-diseases directory.  i don't think you'd be able to load those files into phenote with the disease ontology because ```DOID-DOID:xxxxxxx``` is not a valid curie.

**Comment by tudorgroza** [comment]
sorry ... I was away for a couple of days ... is there something I still have to do w.r.t. the 0-padded DO IDs? Will make sure next time to avoid this issue.
