### ISSUE TITLE
mine disease labels/definitions for phenotypes

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/hpo-annotation-data#86]
there are some diseases for which there are no annotations.  

for example:
http://monarchinitiative.org/disease/DOID:12358

and this also doesn't exist in the "common" annotations.

there is a definition of this disease in DO.  can the definitions be mined for phenotypes?

in this case, it is defined as "A eustachian tube disorder with a wider eustachian tube which allows a larger bolus of bacteria-laden material from the nasopharynx during an infection to enter the middle ear, causing a more fulminant infection."

i could see this mapping at least to:
Abnormality of the eustachian tube ([HP:0040115](http://monarchinitiative.org/phenotype/HP:0040115))

and if that won't work, can we manually add annotations to this repository?

**Comment by cmungall** [comment]
The original plan was for DO to move to editing in github in owl, editing these axioms

I made a start on them in the file ext.owl:
https://github.com/obophenotype/human-disease-ontology/tree/master/src/ontology

(doesn't have eustachian tube tho)

But DO is still in sourceforge editing obo (I had previously helped multiple ontologies make the move to SF, and some to owl at the same time. Don't have the window to do this any more)

We could bring doid/exit across and edit this in Protege, after doing another auto-add using the SG annotator.

We would change the CL and Uberon ones to nested class expressions so that everything would all in the pheno hierarchy. E.g.

    has-phenotype some (has-part some (qualifier abnormal and inheres in some eustachian tube)))

**Comment by drseb** [comment]
@nlwashington yes we agreed that we can manually refine the common-disease annotations now.

**Comment by drseb** [comment]
I have now added 509 new common diseases, where an exact occurrence of an HPO-class-label could be found.

There are more than 2700 candidates (new common diseases, that have no annotation currently) I could send, but this would require more curation (non-exact matches).  There are also a lot of annotations that could be added to existing common disease files. 
Let me know if there are resources available.
@mellybelly this requires **several hours** of biocuration. Any ideas? Split this up among several monarch people?

**Comment by mellybelly** [comment]
@nicolevasilevsky @markengelstad would be happy to help
Need a workflow - @cmungall maybe try PhenoTua?

**Comment by pnrobinson** [comment]
Can we skype about how to move forward here? This could be really valuable!
-peter

Dr. med. Peter N. Robinson, MSc.
Professor of Medical Genomics
Professor of Bioinformatics, Freie Universität Berlin
Institut für Medizinische Genetik und Humangenetik
Charité - Universitätsmedizin Berlin
Augustenburger Platz 1
13353 Berlin
Germany
+4930 450566006
Mobile: 0160 93769872
peter.robinson@charite.de
http://compbio.charite.de
http://www.human-phenotype-ontology.org
I have learned from my mistakes, and I am sure I can repeat them exactly
ORCID ID:http://orcid.org/0000-0002-0736-9199
Scopus Author ID 7403719646
Appointment request: http://doodle.com/pnrobinson
________________________________
Von: Sebastian Köhler [notifications@github.com]
Gesendet: Montag, 16. November 2015 18:20
An: monarch-initiative/hpo-annotation-data
Betreff: Re: [hpo-annotation-data] mine disease labels/definitions for phenotypes (#86)


I have now added 509 new common diseases, where an exact occurrence of an HPO-class-label could be found.

There are more than 2700 candidates (new common diseases, that have no annotation currently) I could send, but this would require more curation (non-exact matches). There are also a lot of annotations that could be added to existing common disease files.
Let me know if there are resources available.
@mellybelly<https://github.com/mellybelly> this requires several hours of biocuration. Any ideas? Split this up among several monarch people?

**Comment by nlwashington** [comment]
@drseb for the new items, i notice you put the DOID as the "pub".  this seems a bit circular, no?  then the disease class is also a publication.  i would consider not doing this.  if you do decide to keep them, can you make these proper curies, as in the prefix for DO is not ```DO:DOID```, rather is simply ```DOID```.  i welcome comments.

**Comment by drseb** [comment]
Well, I fear we do not very often have *publications* in this field (especially for the rare disease). 

I can put ```DO:1234567``` if you prefer.

**Comment by nicolevasilevsky** [comment]
Are we going to have a Skype call to discuss this?

**Comment by drseb** [comment]
next week?

**Comment by nicolevasilevsky** [comment]
Melissa is out of town next week, but I am available. Could we try for Wed, 12/09 at 8am PT? Who do we need on the call?

**Comment by drseb** [comment]
postponed by one week

@pnrobinson @mellybelly

**Comment by nicolevasilevsky** [comment]
the call is scheduled for 12/09 at 9am PT/6pm Berlin

**Comment by cmungall** [comment]
Why don't we get this started with the cases where the disease label equals the phenotype label

**Comment by drseb** [comment]
I have already done this. See https://github.com/monarch-initiative/hpo-annotation-data/commit/2f15bf2c48c77c2308dabef45e65583dac9a8f38

**Comment by cmungall** [comment]
oh nice, for DOIDs too. With clear provenance, great

**Comment by drseb** [comment]
I have done this for common and rare diseases. Only exact matches were considered and afterwards manually checket.
