### ISSUE TITLE
Decipher "syndrome ID" should not be used

### ISSUE THREAD

**Issue by Relequestual** [monarch-initiative/hpo-annotation-data#90]
Came across this in your repo:
https://github.com/monarch-initiative/hpo-annotation-data/blob/master/rare-diseases/annotated/DECIPHER-1.tab

Decipher Syndromes do not have stable IDs. The IDs may change between releases. The IDs used are for internal purposes only, and are not intended for reference use.

**Comment by drseb** [comment]
Thanks @Relequestual 

Do you have any references/documentation for this?
Do you know of alternatives?

**Comment by Relequestual** [comment]
(I work on Decipher!)
I posted this issue because we had a breif discussion some weeks ago that this was happening.

After further discussion with the team, although we hadn't intended for the IDs to be used externally, considering they currently are, we will formally support such, and now consider them stable.

**Comment by drseb** [comment]
Ah ok. Didn't know you work there. 

Thanks for clarification!
