### ISSUE TITLE
232700 unsatisfiable

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/hpo-annotation-data#96]
I think the "NOT hypoglycemia" is coming from an automatic text mining for "Variable hypoglycemia".
I think we can just remove the negative annotation not (hasFeature some Hypoglycemia))

232700
Disease
 and (not (hasFeature some Hypoglycemia))
 and (not (hasFeature some Hyperuricemia))
 and (not (hasFeature some Hyperlipidemia))
 and (not (hasFeature some 'Lactic acidosis'))
 and (hasFeature some 'Autosomal recessive inheritance')
 and (hasFeature some Hypoglycemia)
 and (hasFeature some Hepatomegaly)
 and (hasFeature some 'Increased hepatic glycogen content')
 and (hasFeature some 'Postnatal growth retardation')
 and (hasGermlineMutationIn some PYGL)

**Comment by drseb** [comment]
@pnrobinson made the annotation:

```OMIM:232700	GLYCOGEN STORAGE DISEASE VI					HP:0001943	Hypoglycemia			TAS	TAS				NOT	NOT	Mild	OMIM:232700	HPO:probinson	05.05.2012	```

I will just remove this.
